import Foundation

enum DreamStoreError: LocalizedError {
    case unreadableFile(url: URL, underlying: Error)
    case invalidJSON(url: URL, underlying: Error)
    case unsupportedMemoryVersion(url: URL, found: Int, supported: Int)

    var errorDescription: String? {
        switch self {
        case let .unreadableFile(url, underlying):
            return "Could not read dreaming data at \(url.path): \(underlying.localizedDescription)"
        case let .invalidJSON(url, underlying):
            return "Could not decode dreaming data at \(url.path): \(underlying.localizedDescription)"
        case let .unsupportedMemoryVersion(url, found, supported):
            return "Unsupported dream memory version \(found) at \(url.path); "
                + "this version of LokalBot supports version \(supported)."
        }
    }
}

/// A user-manageable item in the durable work memory. Values identify entries
/// by the same case-insensitive keys the nightly merge uses.
enum DreamMemoryEntry: Equatable, Sendable {
    case project(name: String)
    case goal(text: String)
}

/// Persistence for dreaming artifacts, entirely inside the private storage
/// root (never a user-chosen folder, unlike routines/exports — so plain
/// overwrite is safe and no ownership sidecars are needed):
///
///   dreams/<yyyy-MM-dd>.json   # structured report, source of truth
///   dreams/<yyyy-MM-dd>.md     # human-readable rendering of the same report
///   memory/memory.json         # structured work memory, source of truth
///   memory/memory.md           # human-readable rendering
///
/// A valid report whose embedded day matches its filename doubles as the
/// durable "this day was dreamed" marker the scheduler consults, so a crash
/// between runs never double-dreams and a missed night is retried at launch.
struct DreamStore {
    static let generatedMarker = "<!-- Generated by LokalBot dreaming. -->"
    static let memoryFileName = "memory"

    var root: URL

    var dreamsDirectory: URL { root.appendingPathComponent("dreams", isDirectory: true) }
    var memoryDirectory: URL { root.appendingPathComponent("memory", isDirectory: true) }

    func reportJSONURL(forDayKey key: String) -> URL {
        dreamsDirectory.appendingPathComponent("\(key).json", isDirectory: false)
    }

    func hasReport(forDayKey key: String) -> Bool {
        report(forDayKey: key) != nil
    }

    func report(forDayKey key: String) -> DreamReport? {
        guard let report = optionalDecode(
            DreamReport.self,
            at: reportJSONURL(forDayKey: key)),
              report.day == key,
              (1...DreamReport.currentVersion).contains(report.version) else {
            return nil
        }
        return report
    }

    /// Newest valid report by analyzed day. Day keys sort lexicographically in
    /// chronological order, so candidates are decoded newest-first.
    func latestReport() -> DreamReport? {
        let names = (try? FileManager.default.contentsOfDirectory(atPath: dreamsDirectory.path))
            ?? []
        for name in names.filter({ $0.hasSuffix(".json") }).sorted(by: >) {
            let key = String(name.dropLast(".json".count))
            if let report = report(forDayKey: key) {
                return report
            }
        }
        return nil
    }

    /// The report JSON is the scheduler's durable completion marker, so its
    /// Markdown sibling must be durable before the marker appears.
    func save(_ report: DreamReport) throws {
        try writeMarkdown(report.markdown(),
                          to: dreamsDirectory.appendingPathComponent("\(report.day).md",
                                                                     isDirectory: false))
        try write(report, to: reportJSONURL(forDayKey: report.day))
    }

    /// Processing can finish after a brief was generated (for example after a
    /// parked crash-recovery job is retried). Remove the generated completion
    /// marker first so the scheduler will rebuild that day with fresh artifacts.
    func invalidateReport(forDayKey key: String) throws {
        let fileManager = FileManager.default
        let urls = [
            reportJSONURL(forDayKey: key),
            dreamsDirectory.appendingPathComponent("\(key).md", isDirectory: false),
        ]
        for url in urls where fileManager.fileExists(atPath: url.path) {
            try fileManager.removeItem(at: url)
        }
    }

    func loadMemory() throws -> DreamMemory? {
        let url = memoryDirectory.appendingPathComponent("\(Self.memoryFileName).json",
                                                         isDirectory: false)
        guard let memory = try decodeIfPresent(DreamMemory.self, at: url) else {
            return nil
        }
        guard memory.version == DreamMemory.currentVersion else {
            throw DreamStoreError.unsupportedMemoryVersion(
                url: url,
                found: memory.version,
                supported: DreamMemory.currentVersion)
        }
        return memory
    }

    func save(_ memory: DreamMemory) throws {
        try write(memory,
                  to: memoryDirectory.appendingPathComponent("\(Self.memoryFileName).json",
                                                             isDirectory: false))
        try writeMarkdown(memory.markdown(),
                          to: memoryDirectory.appendingPathComponent("\(Self.memoryFileName).md",
                                                                     isDirectory: false))
    }

    /// Reload before changing a pin so a Settings view cannot overwrite memory
    /// written by a dream since the view appeared. Returns nil when the memory
    /// or selected entry no longer exists.
    @discardableResult
    func setPinned(
        _ pinned: Bool,
        for entry: DreamMemoryEntry,
        at date: Date = Date()
    ) throws -> DreamMemory? {
        guard var memory = try loadMemory() else { return nil }

        switch entry {
        case .project(let name):
            guard let index = memory.activeProjects.firstIndex(where: {
                $0.name.caseInsensitiveCompare(name) == .orderedSame
            }) else { return nil }
            guard memory.activeProjects[index].pinned != pinned else { return memory }
            memory.activeProjects[index].pinned = pinned
        case .goal(let text):
            guard let index = memory.workGoals.firstIndex(where: {
                $0.text.caseInsensitiveCompare(text) == .orderedSame
            }) else { return nil }
            guard memory.workGoals[index].pinned != pinned else { return memory }
            memory.workGoals[index].pinned = pinned
        }

        memory.updatedAt = date
        try save(memory)
        return memory
    }

    /// Persist one complete dream. Memory is committed first, followed by the
    /// report rendering, and the report JSON marker last. Any earlier failure
    /// therefore leaves `hasReport` false so the scheduler can retry safely.
    func save(report: DreamReport, memory: DreamMemory) throws {
        try save(memory)
        try save(report)
    }

    // MARK: - Plumbing

    private func optionalDecode<T: Decodable>(_ type: T.Type, at url: URL) -> T? {
        do {
            return try decodeIfPresent(type, at: url)
        } catch {
            return nil
        }
    }

    private func decodeIfPresent<T: Decodable>(_ type: T.Type, at url: URL) throws -> T? {
        let data: Data
        do {
            data = try Data(contentsOf: url)
        } catch {
            let cocoaError = error as NSError
            let isMissing = cocoaError.code == NSFileNoSuchFileError
                || cocoaError.code == NSFileReadNoSuchFileError
            if cocoaError.domain == NSCocoaErrorDomain,
               isMissing {
                return nil
            }
            throw DreamStoreError.unreadableFile(url: url, underlying: error)
        }

        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .iso8601
        do {
            return try decoder.decode(type, from: data)
        } catch {
            throw DreamStoreError.invalidJSON(url: url, underlying: error)
        }
    }

    private func write<T: Encodable>(_ value: T, to url: URL) throws {
        let encoder = JSONEncoder()
        encoder.dateEncodingStrategy = .iso8601
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
        try writeData(encoder.encode(value), to: url)
    }

    private func writeMarkdown(_ body: String, to url: URL) throws {
        try writeData(Data((Self.generatedMarker + "\n\n" + body + "\n").utf8), to: url)
    }

    private func writeData(_ data: Data, to url: URL) throws {
        let fileManager = FileManager.default
        try fileManager.createDirectory(
            at: url.deletingLastPathComponent(),
            withIntermediateDirectories: true,
            attributes: [.posixPermissions: 0o700])
        try data.write(to: url, options: .atomic)
        try fileManager.setAttributes([.posixPermissions: 0o600], ofItemAtPath: url.path)
    }
}
