import Foundation

/// Persistence for dreaming artifacts, entirely inside the private storage
/// root (never a user-chosen folder, unlike routines/exports — so plain
/// overwrite is safe and no ownership sidecars are needed):
///
///   dreams/<yyyy-MM-dd>.json   # structured report, source of truth
///   dreams/<yyyy-MM-dd>.md     # human-readable rendering of the same report
///   memory/memory.json         # structured work memory, source of truth
///   memory/memory.md           # human-readable rendering
///
/// The report file's existence doubles as the durable "this day was dreamed"
/// marker the scheduler consults, so a crash between runs never double-dreams
/// and a missed night is retried at the next launch.
struct DreamStore {
    static let generatedMarker = "<!-- Generated by LokalBot dreaming. -->"
    static let memoryFileName = "memory"

    var root: URL

    var dreamsDirectory: URL { root.appendingPathComponent("dreams", isDirectory: true) }
    var memoryDirectory: URL { root.appendingPathComponent("memory", isDirectory: true) }

    func reportJSONURL(forDayKey key: String) -> URL {
        dreamsDirectory.appendingPathComponent("\(key).json", isDirectory: false)
    }

    func hasReport(forDayKey key: String) -> Bool {
        FileManager.default.fileExists(atPath: reportJSONURL(forDayKey: key).path)
    }

    func report(forDayKey key: String) -> DreamReport? {
        decode(DreamReport.self, at: reportJSONURL(forDayKey: key))
    }

    /// Newest report by analyzed day. Day keys sort lexicographically in
    /// chronological order, so this is a filename sort — no decoding sweep.
    func latestReport() -> DreamReport? {
        let names = (try? FileManager.default.contentsOfDirectory(atPath: dreamsDirectory.path))
            ?? []
        for name in names.filter({ $0.hasSuffix(".json") }).sorted(by: >) {
            if let report = decode(
                DreamReport.self,
                at: dreamsDirectory.appendingPathComponent(name, isDirectory: false)) {
                return report
            }
        }
        return nil
    }

    /// The report JSON is the scheduler's durable completion marker, so its
    /// Markdown sibling must be durable before the marker appears.
    func save(_ report: DreamReport) throws {
        try writeMarkdown(report.markdown(),
                          to: dreamsDirectory.appendingPathComponent("\(report.day).md",
                                                                     isDirectory: false))
        try write(report, to: reportJSONURL(forDayKey: report.day))
    }

    func loadMemory() -> DreamMemory? {
        decode(DreamMemory.self,
               at: memoryDirectory.appendingPathComponent("\(Self.memoryFileName).json",
                                                          isDirectory: false))
    }

    func save(_ memory: DreamMemory) throws {
        try write(memory,
                  to: memoryDirectory.appendingPathComponent("\(Self.memoryFileName).json",
                                                             isDirectory: false))
        try writeMarkdown(memory.markdown(),
                          to: memoryDirectory.appendingPathComponent("\(Self.memoryFileName).md",
                                                                     isDirectory: false))
    }

    /// Persist one complete dream. Memory is committed first, followed by the
    /// report rendering, and the report JSON marker last. Any earlier failure
    /// therefore leaves `hasReport` false so the scheduler can retry safely.
    func save(report: DreamReport, memory: DreamMemory) throws {
        try save(memory)
        try save(report)
    }

    // MARK: - Plumbing

    private func decode<T: Decodable>(_ type: T.Type, at url: URL) -> T? {
        guard let data = try? Data(contentsOf: url) else { return nil }
        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .iso8601
        return try? decoder.decode(type, from: data)
    }

    private func write<T: Encodable>(_ value: T, to url: URL) throws {
        let encoder = JSONEncoder()
        encoder.dateEncodingStrategy = .iso8601
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
        try writeData(encoder.encode(value), to: url)
    }

    private func writeMarkdown(_ body: String, to url: URL) throws {
        try writeData(Data((Self.generatedMarker + "\n\n" + body + "\n").utf8), to: url)
    }

    private func writeData(_ data: Data, to url: URL) throws {
        let fileManager = FileManager.default
        try fileManager.createDirectory(
            at: url.deletingLastPathComponent(),
            withIntermediateDirectories: true,
            attributes: [.posixPermissions: 0o700])
        try data.write(to: url, options: .atomic)
        try fileManager.setAttributes([.posixPermissions: 0o600], ofItemAtPath: url.path)
    }
}
