import Foundation
import Darwin

enum DreamStoreError: LocalizedError {
    case unreadableFile(url: URL, underlying: Error)
    case invalidJSON(url: URL, underlying: Error)
    case unsupportedMemoryVersion(url: URL, found: Int, supported: Int)
    case evidenceRetractionIncomplete

    var errorDescription: String? {
        switch self {
        case let .unreadableFile(url, underlying):
            return "Could not read dreaming data at \(url.path): \(underlying.localizedDescription)"
        case let .invalidJSON(url, underlying):
            return "Could not decode dreaming data at \(url.path): \(underlying.localizedDescription)"
        case let .unsupportedMemoryVersion(url, found, supported):
            return "Unsupported dream memory version \(found) at \(url.path); "
                + "this version of LokalBot supports version \(supported)."
        case .evidenceRetractionIncomplete:
            return "Dream memory is unavailable because changed evidence could not be retracted. Retry after resolving the storage error."
        }
    }
}

/// A user-manageable item in the durable work memory. Values identify entries
/// by the same case-insensitive keys the nightly merge uses.
enum DreamMemoryEntry: Equatable, Sendable {
    case project(name: String)
    case goal(text: String)
}

/// Persistence for dreaming artifacts, entirely inside the private storage
/// root (never a user-chosen folder, unlike routines/exports — so plain
/// overwrite is safe and no ownership sidecars are needed):
///
///   dreams/<yyyy-MM-dd>.json   # structured report, source of truth
///   dreams/<yyyy-MM-dd>.md     # human-readable rendering of the same report
///   memory/memory.json         # structured work memory, source of truth
///   memory/memory.md           # human-readable rendering
///
/// A valid report whose embedded day matches its filename doubles as the
/// durable "this day was dreamed" marker the scheduler consults, so a crash
/// between runs never double-dreams and a missed night is retried at launch.
struct DreamStore {
    static let generatedMarker = "<!-- Generated by LokalBot dreaming. -->"
    static let memoryFileName = "memory"
    // Store values are created by several services. Serialize the revision
    // check and writes across all instances, not only one scheduler task.
    private static let mutationLock = NSRecursiveLock()
    private static var lockedRoots: Set<String> = []
    private static var blockedRoots: Set<String> = []
    private struct PendingInvalidation: Codable {
        var id: UUID = UUID()
        var days: Set<String> = []
        var meetings: Set<UUID> = []
        var reports: Set<String> = []
        var awaitingSourceMutation = false
        var ownerProcessID: Int32?
        var protectedByMutationLock: Bool?
    }
    private static var pendingInvalidations: [String: PendingInvalidation] = [:]

    private struct EvidenceState: Codable {
        var revision: UInt64 = 0
        var invalidatedDays: [String: UInt64] = [:]
        var invalidatedMeetings: [String: UInt64]?
    }

    var root: URL

    var dreamsDirectory: URL { root.appendingPathComponent("dreams", isDirectory: true) }
    var memoryDirectory: URL { root.appendingPathComponent("memory", isDirectory: true) }
    private var evidenceStateURL: URL { memoryDirectory.appendingPathComponent("evidence-revisions.json") }
    /// Kept outside memory/ so revocation remains durable if that directory
    /// becomes unwritable. Its presence blocks every process until cleanup.
    private var pendingInvalidationURL: URL { root.appendingPathComponent(".dream-revocation-pending.json") }
    private var rootKey: String { root.standardizedFileURL.resolvingSymlinksInPath().path }

    /// Capture this before compiling evidence, then require it when committing.
    func evidenceRevision() throws -> UInt64 {
        try withLock {
            var durable = try pendingIntents()
            var recoveredPreparedIntent = false
            for index in durable.indices where durable[index].awaitingSourceMutation {
                let ownerExited = durable[index].ownerProcessID.map { pid in
                    kill(pid, 0) != 0 && errno == ESRCH
                } ?? false
                // Acquiring this file lock proves a lock-protected mutation is
                // no longer running. Standalone preflights may still be waiting
                // for their source write, so only recover them after owner exit.
                guard durable[index].protectedByMutationLock == true || ownerExited else {
                    throw DreamStoreError.evidenceRetractionIncomplete
                }
                durable[index].awaitingSourceMutation = false
                recoveredPreparedIntent = true
            }
            if recoveredPreparedIntent { try write(durable, to: pendingInvalidationURL) }
            if Self.pendingInvalidations[rootKey] != nil || !durable.isEmpty {
                // "Dream now" and the scheduler's normal retry can recover
                // after storage becomes writable; never silently drop a failed
                // revocation just because the next changed source is different.
                let pending = Self.pendingInvalidations[rootKey] ?? PendingInvalidation()
                try invalidateEvidence(
                    affectedDayKeys: durable.reduce(into: pending.days) { $0.formUnion($1.days) },
                    affectedMeetingIDs: durable.reduce(into: pending.meetings) { $0.formUnion($1.meetings) },
                    reportDayKeys: durable.reduce(into: pending.reports) { $0.formUnion($1.reports) })
            }
            try requireAvailableEvidence()
            return try evidenceState().revision
        }
    }

    func reportJSONURL(forDayKey key: String) -> URL {
        dreamsDirectory.appendingPathComponent("\(key).json", isDirectory: false)
    }

    func hasReport(forDayKey key: String) -> Bool {
        report(forDayKey: key) != nil
    }

    func report(forDayKey key: String) -> DreamReport? {
        (try? withLock {
            guard evidenceIsAvailable,
                  let state = try? evidenceState(),
                  let report = optionalDecode(DreamReport.self, at: reportJSONURL(forDayKey: key)),
                  report.day == key,
                  (1...DreamReport.currentVersion).contains(report.version),
                  !isInvalidated(report.evidenceProvenance, by: state) else {
                return nil
            }
            return report
        }) ?? nil
    }

    /// Newest valid report by analyzed day. Day keys sort lexicographically in
    /// chronological order, so candidates are decoded newest-first.
    func latestReport() -> DreamReport? {
        let names = (try? FileManager.default.contentsOfDirectory(atPath: dreamsDirectory.path))
            ?? []
        for name in names.filter({ $0.hasSuffix(".json") }).sorted(by: >) {
            let key = String(name.dropLast(".json".count))
            if let report = report(forDayKey: key) {
                return report
            }
        }
        return nil
    }

    /// The report JSON is the scheduler's durable completion marker, so its
    /// Markdown sibling must be durable before the marker appears.
    func save(_ report: DreamReport) throws {
        try withLock {
            try requireAvailableEvidence()
            // Direct callers must not restore a previously revoked report either.
            guard !isInvalidated(report.evidenceProvenance, by: try evidenceState()) else {
                throw CancellationError()
            }
            try writeMarkdown(report.markdown(),
                              to: dreamsDirectory.appendingPathComponent("\(report.day).md", isDirectory: false))
            try write(report, to: reportJSONURL(forDayKey: report.day))
        }
    }

    /// Processing can finish after a brief was generated (for example after a
    /// parked crash-recovery job is retried). Remove the generated completion
    /// marker first so the scheduler will rebuild that day with fresh artifacts.
    func invalidateReport(forDayKey key: String) throws {
        try withLock {
            let fileManager = FileManager.default
            let urls = [
                reportJSONURL(forDayKey: key),
                dreamsDirectory.appendingPathComponent("\(key).md", isDirectory: false),
            ]
            for url in urls where fileManager.fileExists(atPath: url.path) {
                try fileManager.removeItem(at: url)
            }
        }
    }

    /// Persist revocation before cleanup. If a later disk write fails, reads
    /// still filter revoked content and an in-flight synthesis cannot commit.
    /// Legacy items/reports have unknown dependencies and are removed on the
    /// first mutation; pins affect retention, never source revocation.
    @discardableResult
    func invalidateEvidence(affectedDayKeys: Set<String>, affectedMeetingIDs: Set<UUID> = [],
                            reportDayKeys: Set<String>,
                            at date: Date = Date()) throws -> Set<String> {
        guard !affectedDayKeys.isEmpty || !affectedMeetingIDs.isEmpty else { return [] }
        Self.mutationLock.lock()
        defer { Self.mutationLock.unlock() }
        var pending = Self.pendingInvalidations[rootKey] ?? PendingInvalidation()
        pending.days.formUnion(affectedDayKeys)
        pending.meetings.formUnion(affectedMeetingIDs)
        pending.reports.formUnion(reportDayKeys)
        do {
            return try withLock {
                // A successful retry may reopen this root. Keep other readers
                // excluded until cleanup has succeeded or the catch blocks it.
                Self.blockedRoots.remove(rootKey)
                var intents = try pendingIntents()
                for index in intents.indices {
                    let matchesCompletedMutation = intents[index].days.isSubset(of: affectedDayKeys)
                        && intents[index].meetings.isSubset(of: affectedMeetingIDs)
                    if !intents[index].awaitingSourceMutation || matchesCompletedMutation {
                        intents[index].awaitingSourceMutation = false
                        pending.days.formUnion(intents[index].days)
                        pending.meetings.formUnion(intents[index].meetings)
                        pending.reports.formUnion(intents[index].reports)
                    }
                }
                intents.append(pending)
                // Durable intent precedes the memory journal. A fresh process
                // must not mistake a journal permission failure for no change.
                try write(intents, to: pendingInvalidationURL)
                var state = try evidenceState()
                guard state.revision < UInt64.max else { throw DreamStoreError.evidenceRetractionIncomplete }
                state.revision += 1
                for day in pending.days { state.invalidatedDays[day] = state.revision }
                var meetings = state.invalidatedMeetings ?? [:]
                for id in pending.meetings { meetings[id.uuidString] = state.revision }
                state.invalidatedMeetings = meetings
                try write(state, to: evidenceStateURL)

                if var memory = try readMemory(state: state) {
                    memory.updatedAt = date
                    try writeMemory(memory, state: state)
                }
                var keys = pending.reports
                let names = (try? FileManager.default.contentsOfDirectory(atPath: dreamsDirectory.path)) ?? []
                for name in names where name.hasSuffix(".json") {
                    let key = String(name.dropLast(".json".count))
                    if let report = optionalDecode(DreamReport.self, at: reportJSONURL(forDayKey: key)),
                       isInvalidated(report.evidenceProvenance, by: state) {
                        keys.insert(key)
                    }
                }
                for key in keys { try invalidateReport(forDayKey: key) }
                let remaining = intents.filter(\.awaitingSourceMutation)
                if remaining.isEmpty {
                    try FileManager.default.removeItem(at: pendingInvalidationURL)
                } else {
                    try write(remaining, to: pendingInvalidationURL)
                }
                Self.pendingInvalidations.removeValue(forKey: rootKey)
                return keys
            }
        } catch {
            // Source mutation precedes this call. If even the journal cannot
            // be written, do not let another store instance read old facts or
            // start inference in this process. The caller surfaces the error.
            Self.blockedRoots.insert(rootKey)
            Self.pendingInvalidations[rootKey] = pending
            throw error
        }
    }

    func loadMemory() throws -> DreamMemory? {
        try withLock {
            guard evidenceIsAvailable else { return nil }
            return try readMemory(state: evidenceState())
        }
    }

    func save(_ memory: DreamMemory) throws {
        try withLock {
            try requireAvailableEvidence()
            try writeMemory(memory, state: evidenceState())
        }
    }

    /// Call before a source write. Failure aborts that write; success leaves a
    /// durable barrier until the matching post-write invalidateEvidence call.
    /// A prepared intent is never consumed by a background inference retry.
    func prepareEvidenceInvalidation(affectedDayKeys: Set<String>, affectedMeetingIDs: Set<UUID> = [],
                                     reportDayKeys: Set<String> = [], protectedByMutationLock: Bool = false) throws {
        guard !affectedDayKeys.isEmpty || !affectedMeetingIDs.isEmpty else { return }
        try withLock {
            var intents = try pendingIntents()
            intents.append(PendingInvalidation(days: affectedDayKeys, meetings: affectedMeetingIDs,
                                               reports: reportDayKeys, awaitingSourceMutation: true,
                                               ownerProcessID: getpid(), protectedByMutationLock: protectedByMutationLock))
            try write(intents, to: pendingInvalidationURL)
        }
    }

    /// Fully retract before changing a source, under the shared app/headless
    /// lock. A cleanup failure leaves the source untouched; a successful source
    /// mutation must not be reported as failed by a later Dream storage error.
    func withEvidenceMutation<T>(affectedDayKeys: Set<String>, affectedMeetingIDs: Set<UUID> = [],
                                 reportDayKeys: Set<String> = [], _ mutation: () throws -> T) throws -> T {
        try withLock {
            try prepareEvidenceInvalidation(affectedDayKeys: affectedDayKeys,
                                            affectedMeetingIDs: affectedMeetingIDs, reportDayKeys: reportDayKeys,
                                            protectedByMutationLock: true)
            try invalidateEvidence(affectedDayKeys: affectedDayKeys,
                                   affectedMeetingIDs: affectedMeetingIDs, reportDayKeys: reportDayKeys)
            // The advanced revision rejects older generations. No new one can
            // acquire its revision until this lock releases after the source
            // write, including nested mutations and partial source failures.
            return try mutation()
        }
    }

    /// Reload before changing a pin so a Settings view cannot overwrite memory
    /// written by a dream since the view appeared. Returns nil when the memory
    /// or selected entry no longer exists.
    @discardableResult
    func setPinned(
        _ pinned: Bool,
        for entry: DreamMemoryEntry,
        at date: Date = Date()
    ) throws -> DreamMemory? {
        try withLock {
            guard var memory = try loadMemory() else { return nil }

            switch entry {
            case .project(let name):
                guard let index = memory.activeProjects.firstIndex(where: {
                    $0.name.caseInsensitiveCompare(name) == .orderedSame
                }) else { return nil }
                guard memory.activeProjects[index].pinned != pinned else { return memory }
                memory.activeProjects[index].pinned = pinned
            case .goal(let text):
                guard let index = memory.workGoals.firstIndex(where: {
                    $0.text.caseInsensitiveCompare(text) == .orderedSame
                }) else { return nil }
                guard memory.workGoals[index].pinned != pinned else { return memory }
                memory.workGoals[index].pinned = pinned
            }

            memory.updatedAt = date
            try save(memory)
            return memory
        }
    }

    /// Persist one complete dream. Memory is committed first, followed by the
    /// report rendering, and the report JSON marker last. Any earlier failure
    /// therefore leaves `hasReport` false so the scheduler can retry safely.
    func save(report: DreamReport, memory: DreamMemory) throws {
        try withLock {
            try save(memory)
            try save(report)
        }
    }

    /// No await can occur between the revision check and the complete commit.
    /// Even a model or headless caller that ignores task cancellation cannot
    /// put a snapshot taken before source revocation back into the store.
    func saveGenerated(report: DreamReport, memory: DreamMemory?, basedOnRevision revision: UInt64) throws {
        try withLock {
            try requireAvailableEvidence()
            guard try evidenceState().revision == revision else { throw CancellationError() }
            if let memory { try save(memory) }
            try save(report)
        }
    }

    // MARK: - Plumbing

    private func evidenceState() throws -> EvidenceState {
        try decodeIfPresent(EvidenceState.self, at: evidenceStateURL) ?? EvidenceState()
    }

    private func pendingIntents() throws -> [PendingInvalidation] {
        try decodeIfPresent([PendingInvalidation].self, at: pendingInvalidationURL) ?? []
    }

    private var evidenceIsAvailable: Bool {
        !Self.blockedRoots.contains(rootKey)
            && !FileManager.default.fileExists(atPath: pendingInvalidationURL.path)
    }

    private func requireAvailableEvidence() throws {
        guard evidenceIsAvailable else { throw DreamStoreError.evidenceRetractionIncomplete }
    }

    private func readMemory(state: EvidenceState) throws -> DreamMemory? {
        let url = memoryDirectory.appendingPathComponent("\(Self.memoryFileName).json", isDirectory: false)
        guard let memory = try decodeIfPresent(DreamMemory.self, at: url) else { return nil }
        guard (1...DreamMemory.currentVersion).contains(memory.version) else {
            throw DreamStoreError.unsupportedMemoryVersion(
                url: url, found: memory.version, supported: DreamMemory.currentVersion)
        }
        return memory.retractingEvidence(invalidations: state.invalidatedDays, revision: state.revision,
                                         meetingInvalidations: state.invalidatedMeetings ?? [:])
    }

    private func writeMemory(_ memory: DreamMemory, state: EvidenceState) throws {
        var memory = memory.retractingEvidence(invalidations: state.invalidatedDays, revision: state.revision,
                                               meetingInvalidations: state.invalidatedMeetings ?? [:])
        memory.version = DreamMemory.currentVersion
        try write(memory, to: memoryDirectory.appendingPathComponent("\(Self.memoryFileName).json", isDirectory: false))
        try writeMarkdown(memory.markdown(),
                          to: memoryDirectory.appendingPathComponent("\(Self.memoryFileName).md", isDirectory: false))
    }

    private func isInvalidated(_ provenance: DreamEvidenceProvenance?, by state: EvidenceState) -> Bool {
        guard state.revision > 0 else { return false }
        guard let provenance else { return true }
        return provenance.isInvalidated(by: state.invalidatedDays, currentRevision: state.revision,
                                        meetingRevisions: state.invalidatedMeetings ?? [:])
    }

    private func withLock<T>(_ body: () throws -> T) throws -> T {
        Self.mutationLock.lock()
        defer { Self.mutationLock.unlock() }
        let key = rootKey
        if Self.lockedRoots.contains(key) { return try body() }
        // The headless runner and app can share a library. An advisory file
        // lock makes revision-check + commit atomic across those processes too.
        try FileManager.default.createDirectory(at: root, withIntermediateDirectories: true,
                                                attributes: [.posixPermissions: 0o700])
        let descriptor = open(root.appendingPathComponent(".dream-store.lock").path,
                              O_RDWR | O_CREAT | O_NOFOLLOW, 0o600)
        guard descriptor >= 0 else { throw POSIXError(POSIXErrorCode(rawValue: errno) ?? .EIO) }
        defer { close(descriptor) }
        guard flock(descriptor, LOCK_EX) == 0 else {
            throw POSIXError(POSIXErrorCode(rawValue: errno) ?? .EIO)
        }
        Self.lockedRoots.insert(key)
        defer {
            Self.lockedRoots.remove(key)
            flock(descriptor, LOCK_UN)
        }
        return try body()
    }

    private func optionalDecode<T: Decodable>(_ type: T.Type, at url: URL) -> T? {
        do {
            return try decodeIfPresent(type, at: url)
        } catch {
            return nil
        }
    }

    private func decodeIfPresent<T: Decodable>(_ type: T.Type, at url: URL) throws -> T? {
        let data: Data
        do {
            data = try Data(contentsOf: url)
        } catch {
            let cocoaError = error as NSError
            let isMissing = cocoaError.code == NSFileNoSuchFileError
                || cocoaError.code == NSFileReadNoSuchFileError
            if cocoaError.domain == NSCocoaErrorDomain,
               isMissing {
                return nil
            }
            throw DreamStoreError.unreadableFile(url: url, underlying: error)
        }

        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .iso8601
        do {
            return try decoder.decode(type, from: data)
        } catch {
            throw DreamStoreError.invalidJSON(url: url, underlying: error)
        }
    }

    private func write<T: Encodable>(_ value: T, to url: URL) throws {
        let encoder = JSONEncoder()
        encoder.dateEncodingStrategy = .iso8601
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
        try writeData(encoder.encode(value), to: url)
    }

    private func writeMarkdown(_ body: String, to url: URL) throws {
        try writeData(Data((Self.generatedMarker + "\n\n" + body + "\n").utf8), to: url)
    }

    private func writeData(_ data: Data, to url: URL) throws {
        let fileManager = FileManager.default
        try fileManager.createDirectory(
            at: url.deletingLastPathComponent(),
            withIntermediateDirectories: true,
            attributes: [.posixPermissions: 0o700])
        try data.write(to: url, options: .atomic)
        try fileManager.setAttributes([.posixPermissions: 0o600], ofItemAtPath: url.path)
    }
}
