import CryptoKit
import Foundation

enum DailyMemoryExportKind: String, Codable, CaseIterable, Sendable {
    case markdown
    case obsidian
    case logseq
}

struct DailyMemoryExportConfiguration: Equatable {
    var destinationDirectory: URL
    var format: DailyMemoryExportKind
}

enum DailyMemoryExportError: LocalizedError, Equatable {
    case destinationCollision(URL)
    case generatedFileModified(URL)

    var errorDescription: String? {
        switch self {
        case .destinationCollision(let url):
            "Daily memory export stopped because \(url.lastPathComponent) already exists "
                + "and was not generated by LokalBot. Choose another folder or move that file."
        case .generatedFileModified(let url):
            "Daily memory export stopped because \(url.lastPathComponent) was edited after "
                + "LokalBot generated it. Your edits were preserved; move the file or choose "
                + "another export folder to resume automatic refreshes."
        }
    }
}

struct DailyMemoryMeetingReference: Equatable {
    var id: String
    var title: String
    var startedAt: Date
    var durationSeconds: TimeInterval
}

struct DailyMemoryExportSnapshot: Equatable {
    var day: Date
    var digest: String?
    var meetings: [DailyMemoryMeetingReference]
    var savedMoments: [ScreenMemorySavedMoment]
    var stats: ScreenMemoryDaySummary
    var appUsage: [ScreenMemoryAppUsage]
}

/// Injection seam keeps rendering and atomic file behavior testable without a
/// live meeting library or SQLite database.
protocol DailyMemoryExportSource {
    func snapshot(for day: Date, interval: DateInterval) throws -> DailyMemoryExportSnapshot
}

/// Default source for the scheduler: existing journal Markdown plus read-only
/// meeting and screen-memory queries. Screen data is optional when day tracking
/// has never created a database; an existing-but-unreadable database still
/// fails loudly instead of silently publishing incomplete data.
struct FileDailyMemoryExportSource: DailyMemoryExportSource {
    var root: URL
    var screenReader: any ScreenMemoryReading

    init(
        root: URL = SessionLookup.storageRootURL,
        screenReader: (any ScreenMemoryReading)? = nil
    ) {
        self.root = root
        self.screenReader = screenReader ?? SQLiteScreenMemoryReader(
            databaseURL: root.appendingPathComponent("lokalbotv3.sqlite"))
    }

    func snapshot(for day: Date, interval: DateInterval) throws -> DailyMemoryExportSnapshot {
        let dayName = Self.dayName(day, calendar: .current)
        let digestURL = root.appendingPathComponent("journal/\(dayName).md")
        let digest: String?
        if FileManager.default.fileExists(atPath: digestURL.path) {
            digest = try String(contentsOf: digestURL, encoding: .utf8)
        } else {
            digest = nil
        }

        let meetings = try SessionLookup.loadAllMeetings(root: root)
            .filter { interval.contains($0.startedAt) }
            .sorted { $0.startedAt < $1.startedAt }
            .map {
                DailyMemoryMeetingReference(
                    id: SessionLookup.shortID($0.id),
                    title: $0.title,
                    startedAt: $0.startedAt,
                    durationSeconds: $0.duration ?? 0)
            }

        let databaseURL = root.appendingPathComponent("lokalbotv3.sqlite")
        let moments: [ScreenMemorySavedMoment]
        let stats: ScreenMemoryDaySummary
        let usage: [ScreenMemoryAppUsage]
        if FileManager.default.fileExists(atPath: databaseURL.path) {
            moments = try screenReader.savedMoments(
                from: interval.start, to: interval.end, limit: 500)
            stats = try screenReader.daySummary(from: interval.start, to: interval.end)
            usage = try screenReader.appUsage(
                from: interval.start, to: interval.end, limit: 100)
        } else {
            moments = []
            stats = ScreenMemoryDaySummary(
                trackedSeconds: 0,
                appCount: 0,
                activityBlockCount: 0,
                screenshotCount: 0,
                savedMomentCount: 0)
            usage = []
        }

        return DailyMemoryExportSnapshot(
            day: day,
            digest: digest,
            meetings: meetings,
            savedMoments: moments,
            stats: stats,
            appUsage: usage)
    }

    private static func dayName(_ day: Date, calendar: Calendar) -> String {
        let parts = calendar.dateComponents([.year, .month, .day], from: day)
        return String(format: "%04d-%02d-%02d", parts.year ?? 0, parts.month ?? 0,
                      parts.day ?? 0)
    }
}

struct DailyMemoryExportService {
    static let generatedFileMarker = "<!-- Generated by LokalBot daily memory export. -->"
    static let ownershipSidecarSuffix = ".lokalbot-generated.sha256"

    enum Outcome: Equatable {
        case written(URL)
        case unchanged(URL)
    }

    var source: any DailyMemoryExportSource
    var calendar: Calendar
    var fileManager: FileManager

    init(
        source: any DailyMemoryExportSource,
        calendar: Calendar = .current,
        fileManager: FileManager = .default
    ) {
        self.source = source
        self.calendar = calendar
        self.fileManager = fileManager
    }

    /// Rewrites one deterministic day file. A hidden sidecar records the hash
    /// of the exact bytes last emitted by LokalBot. Refresh is allowed only if
    /// the current file still matches that hash, so a user edit made after
    /// generation is never overwritten. Identical content keeps its mtime;
    /// changed app-owned content uses same-directory atomic replacement.
    func export(day: Date, configuration: DailyMemoryExportConfiguration) throws -> Outcome {
        let start = calendar.startOfDay(for: day)
        let end = calendar.date(byAdding: .day, value: 1, to: start)
            ?? start.addingTimeInterval(86_400)
        let snapshot = try source.snapshot(
            for: start,
            interval: DateInterval(start: start, end: end))
        let text = render(snapshot, format: configuration.format)
        let data = Data(text.utf8)
        let outputURL = configuration.destinationDirectory.appendingPathComponent(
            fileName(for: start, format: configuration.format),
            isDirectory: false)
        let sidecarURL = Self.ownershipSidecarURL(for: outputURL)
        let newDigest = Self.digest(data)

        try Task.checkCancellation()
        try fileManager.createDirectory(
            at: configuration.destinationDirectory,
            withIntermediateDirectories: true)
        if fileManager.fileExists(atPath: outputURL.path) {
            let existing = try Data(contentsOf: outputURL)
            let existingText = String(decoding: existing, as: UTF8.self)
            guard existingText.contains(Self.generatedFileMarker) else {
                throw DailyMemoryExportError.destinationCollision(outputURL)
            }
            let recordedDigest = try ownershipDigest(at: sidecarURL)
            if existing == data {
                // Adopt marker-bearing files from the pre-sidecar release, or
                // repair a missing/corrupt sidecar, without touching the note.
                try hardenPermissions(of: outputURL)
                if recordedDigest != newDigest {
                    try writeOwnershipDigest(newDigest, to: sidecarURL)
                } else {
                    try hardenPermissions(of: sidecarURL)
                }
                return .unchanged(outputURL)
            }
            guard recordedDigest == Self.digest(existing) else {
                throw DailyMemoryExportError.generatedFileModified(outputURL)
            }
            // Narrow the read/check/write race: if another process changed the
            // note after validation, fail closed instead of replacing it.
            try Task.checkCancellation()
            guard try Data(contentsOf: outputURL) == existing else {
                throw DailyMemoryExportError.generatedFileModified(outputURL)
            }
        }

        try Task.checkCancellation()
        try data.write(to: outputURL, options: .atomic)
        // Once bytes are committed, always finish tightening their mode even
        // if cancellation arrives between the write and chmod. Otherwise an
        // opt-out race could leave a newly-created note at ambient umask.
        try setPrivatePermissions(of: outputURL)
        try writeOwnershipDigest(newDigest, to: sidecarURL)
        return .written(outputURL)
    }

    static func ownershipSidecarURL(for outputURL: URL) -> URL {
        outputURL.deletingLastPathComponent().appendingPathComponent(
            ".\(outputURL.lastPathComponent)\(ownershipSidecarSuffix)")
    }

    private func ownershipDigest(at url: URL) throws -> String? {
        guard fileManager.fileExists(atPath: url.path) else { return nil }
        let record = try String(contentsOf: url, encoding: .utf8)
            .trimmingCharacters(in: .whitespacesAndNewlines)
        guard record.hasPrefix("v1:"), record.count == 67 else { return nil }
        let digest = String(record.dropFirst(3))
        guard digest.allSatisfy(\.isHexDigit) else { return nil }
        return digest.lowercased()
    }

    private func writeOwnershipDigest(_ digest: String, to url: URL) throws {
        try Task.checkCancellation()
        try Data("v1:\(digest)\n".utf8).write(to: url, options: .atomic)
        // As with the note itself, do not let post-write cancellation skip the
        // permission hardening for a sidecar that now exists on disk.
        try setPrivatePermissions(of: url)
    }

    private func hardenPermissions(of url: URL) throws {
        try Task.checkCancellation()
        try setPrivatePermissions(of: url)
    }

    private func setPrivatePermissions(of url: URL) throws {
        try fileManager.setAttributes(
            [.posixPermissions: 0o600],
            ofItemAtPath: url.path)
    }

    private static func digest(_ data: Data) -> String {
        SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined()
    }

    func render(_ snapshot: DailyMemoryExportSnapshot, format: DailyMemoryExportKind) -> String {
        var sections: [String] = []
        let key = dayKey(snapshot.day, separator: "-")
        switch format {
        case .markdown:
            sections.append("""
                \(Self.generatedFileMarker)

                # Daily memory — \(displayDate(snapshot.day))
                """)
        case .obsidian:
            sections.append("""
                ---
                date: \(key)
                tags:
                  - lokalbot/daily-memory
                source: LokalBot
                ---

                \(Self.generatedFileMarker)

                # Daily memory — \(displayDate(snapshot.day))
                """)
        case .logseq:
            sections.append("""
                title:: Daily memory — \(displayDate(snapshot.day))
                date:: \(key)
                tags:: lokalbot, daily-memory

                \(Self.generatedFileMarker)

                # Daily memory — \(displayDate(snapshot.day))
                """)
        }

        let digest = snapshot.digest?
            .trimmingCharacters(in: .whitespacesAndNewlines)
        sections.append("## Digest\n\n" + ((digest?.isEmpty == false)
            ? digest!
            : "_No day digest was generated._"))
        sections.append(meetingsSection(snapshot.meetings))
        sections.append(savedMomentsSection(snapshot.savedMoments))
        sections.append(statsSection(snapshot))
        return sections.joined(separator: "\n\n") + "\n"
    }

    private func meetingsSection(_ meetings: [DailyMemoryMeetingReference]) -> String {
        guard !meetings.isEmpty else { return "## Meetings\n\n_No meetings._" }
        let rows = meetings.map { meeting in
            "- **\(time(meeting.startedAt))** — \(inline(meeting.title)) · "
                + "\(duration(meeting.durationSeconds)) (`\(meeting.id)`)"
        }
        return "## Meetings\n\n" + rows.joined(separator: "\n")
    }

    private func savedMomentsSection(_ moments: [ScreenMemorySavedMoment]) -> String {
        guard !moments.isEmpty else { return "## Saved moments\n\n_No saved moments._" }
        let rows = moments.map { moment -> String in
            let title = moment.windowTitle.isEmpty
                ? inline(moment.app)
                : "\(inline(moment.app)) — \(inline(moment.windowTitle))"
            var lines = [
                "- **\(time(moment.capturedAt))** — \(title) (`screen:\(moment.snapshotID)`)",
            ]
            let note = singleLine(moment.note)
            if !note.isEmpty { lines.append("  - Note: \(inline(note))") }
            let excerpt = singleLine(moment.ocrExcerpt)
            if !excerpt.isEmpty { lines.append("  - OCR: \(inline(excerpt))") }
            return lines.joined(separator: "\n")
        }
        return "## Saved moments\n\n" + rows.joined(separator: "\n")
    }

    private func statsSection(_ snapshot: DailyMemoryExportSnapshot) -> String {
        let stats = snapshot.stats
        var lines = [
            "## Day stats",
            "",
            "| Metric | Value |",
            "| --- | ---: |",
            "| Tracked time | \(duration(stats.trackedSeconds)) |",
            "| Apps | \(stats.appCount) |",
            "| Activity blocks | \(stats.activityBlockCount) |",
            "| Screenshots | \(stats.screenshotCount) |",
            "| Saved moments | \(stats.savedMomentCount) |",
            "| Meetings | \(snapshot.meetings.count) |",
        ]
        if !snapshot.appUsage.isEmpty {
            lines.append(contentsOf: ["", "### App usage", ""])
            lines += snapshot.appUsage.map {
                "- \(inline($0.app)): \(duration($0.durationSeconds))"
            }
        }
        return lines.joined(separator: "\n")
    }

    private func fileName(for day: Date, format: DailyMemoryExportKind) -> String {
        let separator: Character = format == .logseq ? "_" : "-"
        return dayKey(day, separator: separator) + ".md"
    }

    private func dayKey(_ date: Date, separator: Character) -> String {
        let components = calendar.dateComponents([.year, .month, .day], from: date)
        return String(
            format: "%04d\(separator)%02d\(separator)%02d",
            components.year ?? 0, components.month ?? 0, components.day ?? 0)
    }

    private func displayDate(_ date: Date) -> String {
        let formatter = DateFormatter()
        formatter.calendar = calendar
        formatter.timeZone = calendar.timeZone
        formatter.locale = Locale(identifier: "en_US_POSIX")
        formatter.dateFormat = "MMMM d, yyyy"
        return formatter.string(from: date)
    }

    private func time(_ date: Date) -> String {
        let formatter = DateFormatter()
        formatter.calendar = calendar
        formatter.timeZone = calendar.timeZone
        formatter.locale = Locale(identifier: "en_US_POSIX")
        formatter.dateFormat = "HH:mm"
        return formatter.string(from: date)
    }

    private func duration(_ seconds: TimeInterval) -> String {
        let minutes = max(0, Int(seconds.rounded()) / 60)
        if minutes >= 60 { return "\(minutes / 60)h \(minutes % 60)m" }
        return "\(minutes)m"
    }

    private func singleLine(_ value: String) -> String {
        value.split(whereSeparator: \Character.isWhitespace)
            .joined(separator: " ")
    }

    private func inline(_ value: String) -> String {
        value
            .replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "`", with: "\\`")
            .replacingOccurrences(of: "*", with: "\\*")
            .replacingOccurrences(of: "_", with: "\\_")
            .replacingOccurrences(of: "[", with: "\\[")
            .replacingOccurrences(of: "]", with: "\\]")
            .replacingOccurrences(of: "|", with: "\\|")
    }
}
