"""Per-competitor content for the web/lokalbot-vs-*.html comparison pages.

Rendered by Scripts/render_web.py into web/, where the HTML stays checked in.
To change a page: edit this file (or Scripts/compare.template.html for the
shared markup), run `python3 Scripts/render_web.py`, and commit the
regenerated HTML.

All values are raw HTML fragments inserted into the template without
escaping. "table_rows" entries are (feature, LokalBot cell, competitor cell)
tuples. Each page's "h1" doubles as its link text in the other pages'
"More comparisons" nav and, minus the "LokalBot " prefix, in the footer's
Compare column; the PAGES order sets the order of those links.

VERIFIED is the date every page's competitor details were last checked. It
feeds the "Last verified" line, the disclaimer's month, and dateModified in
the structured data, so bump it only after re-checking all pages.
"""

VERIFIED = "2026-09-24"

CHECK = '<i class="ph ph-check" aria-hidden="true"></i>'
CROSS = '<i class="ph ph-x" aria-hidden="true"></i>'

# Shared LokalBot cells
LB_ASR = "On your Mac — Qwen3-ASR by default, with Parakeet, Granite Speech, and Whisper as alternatives"
LB_DICTATION = f"{CHECK}Hold ⌥ Space in any app"
LB_TIMELINE = f"{CHECK}App and window activity by default; screen text and encrypted screenshots are opt-in and deleted after 14 days"
LB_COTYPING = f"{CHECK}Cotyping, in almost any app"
LB_AGENTS = "Read-only CLI and MCP server, off until you enable Agent Access"
LB_PLATFORM = "macOS 15+ on Apple Silicon"
NO = f"{CROSS}No"

PAGES = [
    {
        "slug": "lokalbot-vs-granola",
        "title": "LokalBot vs Granola: the on-device, open-source alternative",
        "description": "Compare Granola's cloud AI notepad with LokalBot's bot-free, on-device meeting notes for Mac. Free, open source, and no account.",
        "og_title": "LokalBot vs Granola — the on-device alternative",
        "og_description": "Same bot-free meeting notes, with built-in transcription and summaries on your Mac. Free, open source, no account.",
        "h1": "LokalBot vs Granola",
        "competitor_name": "Granola",
        "competitor_column": "Granola",
        "published": "2026-07-01",
        "lead": "Granola is one of the most polished AI notepads around — bot-free capture, great templates, strong team features, and apps on desktop and phone. The trade-off is that your meetings are processed in the cloud, under an account. LokalBot keeps the bot-free workflow but transcribes and summarizes on your Mac by default: no account, no LokalBot backend, and remote inference only when you approve the server.",
        "table_rows": [
            ("Where the AI runs", "On your Mac — Qwen3-ASR speech model by default and llama.cpp summaries", "In the cloud, via third-party AI providers"),
            ("Account required", f"{CROSS}None", f"{CHECK}Yes"),
            ("Works offline", f"{CHECK}Fully, after a one-time model download", "Needs a connection for AI notes"),
            ("Bot-free meeting capture", f"{CHECK}Microphone + selected-app system audio; labels show capture source, not identity", f"{CHECK}Yes — no bot joins your call"),
            ("Model training on your data", "No LokalBot training pipeline or telemetry; approved remote servers have their own terms", '<span class="dim">Opt-out of model training on every plan</span>'),
            ("Meeting history", "Unlimited, stored on your Mac", "Basic: 30 days · Business and Enterprise: unlimited"),
            ("Compliance", "No LokalBot server ever holds your meetings", "SOC 2 Type II; HIPAA workspaces on Enterprise"),
            ("Connect AI tools", LB_AGENTS, "MCP for Claude, ChatGPT, and others; API on paid plans"),
            ("System-wide dictation", LB_DICTATION, NO),
            ("Day timeline", LB_TIMELINE, NO),
            ("Writing autocomplete", LB_COTYPING, NO),
            ("Source code", "Open source, GPLv3", "Proprietary"),
            ("Price", "Free", "Basic free · Business $14 per user/mo · Enterprise $35 per user/mo"),
            ("Platforms", LB_PLATFORM, "Desktop, iOS, Android, and Apple Watch apps"),
        ],
        "competitor_pick_title": "Pick Granola if&hellip;",
        "competitor_pick_sub": "It is a genuinely good product — these are real advantages.",
        "competitor_pick_items": [
            "You want shared folders, team workspaces, and admin controls",
            "You take notes on your phone or watch too",
            "You prefer AI-polished typed notes over full transcripts",
            "You need a vendor with SOC 2 Type II and HIPAA-ready workspaces",
        ],
        "lokal_pick_sub": "Built for when the content of your meetings must stay yours.",
        "lokal_pick_items": [
            "Your meetings can't leave the machine — legal, health, finance, source protection",
            "You want no account and no per-seat subscription — it's free",
            "You want dictation, a day timeline, and autocomplete in the same app",
            "You want source code you — or your security team — can read",
        ],
        "faq": [
            ("Isn't bot-free capture the differentiator?", "Not anymore — Granola and several others skip the meeting bot now. The differentiator is where processing happens. LokalBot transcribes and summarizes on the Mac with its built-in default; if you opt into a remote inference server, it receives the request context."),
            ("What does LokalBot send over the network?", "Model downloads, update checks, optional Agent Mode setup, and remote inference origins you explicitly approve. Audio stays on the Mac; built-in inference keeps transcript and workday context there too."),
            ("Can I try LokalBot next to Granola?", "Yes. LokalBot is free — run it on your next few meetings and compare the notes. Neither app puts a bot in your call, so nobody on the call will notice either one."),
        ],
        "cta_title": "Keep your meetings on your Mac.",
        "disclaimer": "Granola is a trademark of its owner; LokalBot is not affiliated with or endorsed by it. Details are based on public pages and pricing",
    },
    {
        "slug": "lokalbot-vs-otter",
        "title": "LokalBot vs Otter.ai: bot-free, on-device meeting notes",
        "description": "Compare Otter.ai's cloud meeting assistant with LokalBot: no bot in the call, on-device transcription and summaries, no account. Free and open source.",
        "og_title": "LokalBot vs Otter.ai — meeting notes without the bot",
        "og_description": "Otter joins your calls and transcribes in the cloud. LokalBot captures from your Mac and keeps notes on it. Free, open source, no account.",
        "h1": "LokalBot vs Otter",
        "competitor_name": "Otter.ai",
        "competitor_column": "Otter.ai",
        "published": "2026-09-24",
        "lead": "Otter is one of the best-known AI notetakers: its assistant joins Zoom, Microsoft Teams, and Google Meet, transcribes in the cloud, and shares notes with your team. That reach comes with a participant in your call and your conversations on Otter's servers. LokalBot takes the opposite approach: it captures the call from your Mac's own audio, transcribes and summarizes on the Mac, and needs no account.",
        "table_rows": [
            ("How it captures a meeting", f"{CHECK}Microphone + selected-app system audio on your Mac; source labels do not identify speakers", "The Otter assistant joins Zoom, Teams, and Google Meet; its apps can also record directly"),
            ("Where transcription runs", LB_ASR, "Otter's cloud"),
            ("Account required", f"{CROSS}None", f"{CHECK}Yes"),
            ("Works offline", f"{CHECK}After a one-time model download", "Needs a connection"),
            ("Transcription languages", "52 languages and dialects with the default model; 99 with Whisper", "English, Spanish, French, German, Japanese, and Chinese"),
            ("Free plan limits", "None — the whole app is free", "300 transcription minutes per month"),
            ("Team features", "Single-user; share by exporting Markdown", "Shared notes, team workspaces, and integrations"),
            ("Connect AI tools", LB_AGENTS, "Otter MCP server"),
            ("System-wide dictation", LB_DICTATION, NO),
            ("Day timeline", LB_TIMELINE, NO),
            ("Source code", "Open source, GPLv3", "Proprietary"),
            ("Price", "Free", "Basic free · Pro $16.99/mo, or $8.33/mo billed annually · Business $30/mo, or $19.99/mo billed annually · Enterprise custom"),
            ("Platforms", LB_PLATFORM, "Web, Mac and Windows apps, iOS, Android, and a Chrome extension"),
        ],
        "competitor_pick_title": "Pick Otter if&hellip;",
        "competitor_pick_sub": "The cloud notetaker most teams already know.",
        "competitor_pick_items": [
            "Your team wants shared, searchable call notes in one workspace",
            "You also work on Windows, the web, or your phone",
            "A visible assistant in the call suits your meeting culture",
            "You want integrations and admin controls out of the box",
        ],
        "lokal_pick_sub": "For conversations that shouldn't live on someone else's server.",
        "lokal_pick_items": [
            "Nothing joins your call and nothing shows up in the participant list",
            "Client, patient, or source conversations must stay on your Mac",
            "You want no minute caps, no account, and no subscription",
            "You want dictation and a day timeline in the same app",
        ],
        "faq": [
            ("Does LokalBot join my calls like Otter does?", "No. Nothing joins the call and nothing appears in the participant list. LokalBot records your microphone and your Mac's system audio, so it works with Zoom, Teams, Meet, Slack huddles, or any app that plays sound. You're still responsible for telling participants you're recording."),
            ("Is on-device transcription accurate enough?", 'For most meetings, yes — but test it on your own audio. LokalBot defaults to Qwen3-ASR and lets you switch to Parakeet, Granite Speech, or Whisper in Settings. The <a href="benchmarks">benchmarks page</a> shows speed and error rates for the models the project has tested.'),
            ("What does LokalBot cost after the free tier?", "There is no tier. LokalBot is free and open source under GPLv3, with no minute caps, no account, and no subscription."),
        ],
        "cta_title": "Meeting notes, without the bot.",
        "disclaimer": "Otter and Otter.ai are trademarks of their owner; LokalBot is not affiliated with or endorsed by it. Details are based on public pages and pricing",
    },
    {
        "slug": "lokalbot-vs-fireflies",
        "title": "LokalBot vs Fireflies.ai: meeting notes without the bot",
        "description": "Compare Fireflies.ai's cloud meeting notetaker with LokalBot's bot-free, on-device meeting notes for Mac. Free, open source, and no account required.",
        "og_title": "LokalBot vs Fireflies.ai — meeting notes without the bot",
        "og_description": "Fireflies is built for team call libraries in the cloud. LokalBot keeps bot-free meeting notes on your Mac. Free and open source.",
        "h1": "LokalBot vs Fireflies",
        "competitor_name": "Fireflies.ai",
        "competitor_column": "Fireflies.ai",
        "published": "2026-09-24",
        "lead": "Fireflies is built for teams: its notetaker joins your calls, transcribes in more than 100 languages, and pushes notes into CRMs and project tools. If your company runs on a shared call library, it's a strong choice. LokalBot is for the opposite need — notes that stay on your Mac. It captures the call from your Mac's audio with no bot, and runs transcription and summaries locally.",
        "table_rows": [
            ("How it captures a meeting", f"{CHECK}Mic + system audio on your Mac — nothing joins the call", "A notetaker joins Zoom, Google Meet, Teams, and more; the Chrome extension can capture without it"),
            ("Where transcription runs", LB_ASR, "Fireflies' cloud"),
            ("Account required", f"{CROSS}None", f"{CHECK}Yes"),
            ("Works offline", f"{CHECK}After a one-time model download", "Needs a connection"),
            ("Transcription languages", "52 languages and dialects with the default model; 99 with Whisper", "100+"),
            ("Storage", "Limited only by your disk", "Free: 400 minutes per team · Pro: 8,000 minutes per seat · Business and up: unlimited"),
            ("Integrations", "Markdown export, a daily memory note, and a read-only CLI and MCP server", "CRMs, project tools, and an API"),
            ("Compliance", "No LokalBot server ever holds your meetings", "HIPAA compliance and private storage on Enterprise"),
            ("System-wide dictation", LB_DICTATION, NO),
            ("Day timeline", LB_TIMELINE, NO),
            ("Source code", "Open source, GPLv3", "Proprietary"),
            ("Price", "Free", "Free · Pro $10/seat/mo annually ($18 monthly) · Business $19 ($29 monthly) · Enterprise $39, annual only"),
            ("Platforms", LB_PLATFORM, "Web, desktop, iOS, Android, and a Chrome extension"),
        ],
        "competitor_pick_title": "Pick Fireflies if&hellip;",
        "competitor_pick_sub": "A team call library with a lot of plumbing.",
        "competitor_pick_items": [
            "You want every sales or support call logged to your CRM automatically",
            "Your calls span 100+ languages",
            "You need SSO, audit logs, and admin roles for a large team",
            "You work across Windows, the web, and your phone",
        ],
        "lokal_pick_sub": "For the calls you'd rather not upload.",
        "lokal_pick_items": [
            "Your calls involve clients, patients, or sources whose words can't go to a third-party cloud",
            "No bot means no &ldquo;who invited the notetaker?&rdquo; moment",
            "Free forever — no seats, no storage minutes",
            "Dictation, a day timeline, and autocomplete come in the same app",
        ],
        "faq": [
            ("Why not use Fireflies without the bot?", "You can capture without the bot through Fireflies' Chrome extension, but the recording is still processed and stored in Fireflies' cloud under your account. LokalBot keeps the audio, transcript, and summary on your Mac."),
            ("Can LokalBot push notes into my CRM?", "Not directly. LokalBot exports meetings as Markdown, can write a daily memory note to a folder, and exposes a read-only CLI and MCP server so local tools and agents can read your library. Anything beyond that is up to you."),
            ("Will people on the call know LokalBot is recording?", "No — nothing appears in the call, which is why you need to tell participants yourself. On a fresh install, LokalBot asks through a notification before it records a detected meeting."),
        ],
        "cta_title": "Meeting notes that stay on your Mac.",
        "disclaimer": "Fireflies and Fireflies.ai are trademarks of their owner; LokalBot is not affiliated with or endorsed by it. Details are based on public pages and pricing",
    },
    {
        "slug": "lokalbot-vs-hyprnote",
        "title": "LokalBot vs Hyprnote (anarlog): open-source local notes",
        "description": "Compare two open-source, local-first meeting notetakers: LokalBot and Hyprnote, now anarlog. Built-in local AI, cloud options, storage, license, and scope.",
        "og_title": "LokalBot vs Hyprnote (anarlog) — two open-source local notetakers",
        "og_description": "Both are open source and local-first. They differ on scope, built-in local AI vs bring-your-own, platforms, and license.",
        "h1": "LokalBot vs Hyprnote",
        "competitor_name": "Hyprnote (anarlog)",
        "competitor_column": "Hyprnote (anarlog)",
        "published": "2026-07-01",
        "lead": "Hyprnote is the closest cousin on this list: open-source, local-first meeting notes — it helped prove the category. The app is now called anarlog, and hyprnote.com redirects to char.com, the team's newer product. The MIT-licensed anarlog app remains maintained, and it's good. Here's how LokalBot differs.",
        "table_rows": [
            ("Scope", "Meetings, dictation, day timeline, autocomplete, and chat in one app", "Meeting notetaker"),
            ("Transcription", f"{CHECK}{LB_ASR}", f"{CHECK}On-device models on supported Macs, or a cloud provider you select"),
            ("Summaries and chat", f"{CHECK}llama.cpp built in — works with no keys and no setup", "Your choice: a local server such as Ollama or LM Studio, your own API key, Apple Intelligence, or optional hosted AI"),
            ("Cloud features", "None — no account and no sync service; a remote inference server needs your approval", "Opt-in hosted AI, encrypted CloudSync, and sharing"),
            ("Notes on disk", "Local SQLite library with full-text and vector search; Markdown export", "Local SQLite plus plain files; Markdown export"),
            ("Connect AI tools", LB_AGENTS, "Local CLI and MCP server"),
            ("System-wide dictation", LB_DICTATION, NO),
            ("Day timeline", LB_TIMELINE, NO),
            ("Writing autocomplete", LB_COTYPING, NO),
            ("License", "GPLv3 — every fork's improvements stay open", "MIT for the community app; enterprise components are commercially licensed"),
            ("Direction", "Independent, local by default", "Maintained as the community notetaker; the team now builds Char"),
            ("Platforms", LB_PLATFORM, "macOS, Windows, and Linux"),
        ],
        "competitor_pick_title": "Pick Hyprnote if&hellip;",
        "competitor_pick_sub": "A kindred project with different choices — all defensible.",
        "competitor_pick_items": [
            "You need the same notetaker on Windows or Linux",
            "You already run Ollama or have LLM API keys you like",
            "You want optional cloud sync and note sharing",
            "You prefer the MIT license",
        ],
        "lokal_pick_sub": "Local AI with the batteries included, and a wider brief.",
        "lokal_pick_items": [
            "You want zero setup: recommended models in-app, no keys, no separate LLM runner",
            "You want meetings plus dictation, a day timeline, and autocomplete",
            "Copyleft matters: GPLv3 keeps every fork's improvements open",
            "You want transcripts, notes, and your screen activity searchable in one place",
        ],
        "faq": [
            ("Aren't you basically the same project?", "We overlap on the part that matters — local, bot-free meeting notes — and that's a good thing; the category needs more of it. We differ on scope (a workspace vs a notetaker), on shipped local AI vs bring-your-own model, on platforms, and on license."),
            ("What's Char?", "The team's current product: an AI notepad in private beta at char.com, backed by Y Combinator. It's a separate codebase from the open-source anarlog app, which the team says remains maintained."),
            ("Why GPLv3 instead of MIT?", "Copyleft. Anyone can fork LokalBot, but improvements have to stay open. For an app that hears your meetings and reads your screen, we want the audit path to survive every fork — the code you can read should always be the code you run."),
        ],
        "cta_title": "Local AI, batteries included.",
        "disclaimer": "Hyprnote, anarlog, and Char are trademarks of their owners; LokalBot is not affiliated with or endorsed by them. Details are based on their public repository and sites",
    },
    {
        "slug": "lokalbot-vs-macwhisper",
        "title": "LokalBot vs MacWhisper: local transcription on Mac compared",
        "description": "Compare MacWhisper's file transcription and dictation with LokalBot's free, open-source Mac app for bot-free meeting notes, dictation, and day recall.",
        "og_title": "LokalBot vs MacWhisper — local transcription on Mac compared",
        "og_description": "MacWhisper is the file-transcription specialist. LokalBot is built around meeting notes and recall. Both run on your Mac.",
        "h1": "LokalBot vs MacWhisper",
        "competitor_name": "MacWhisper",
        "competitor_column": "MacWhisper",
        "published": "2026-09-24",
        "lead": "MacWhisper is the go-to Mac app for transcribing files: drag in an interview, lecture, or podcast and get text back, on-device. It also records calls without a bot and offers dictation. LokalBot overlaps on meetings and dictation but is built around recall rather than files — meeting notes with local summaries, a searchable library, and a day timeline. LokalBot is free and open source; MacWhisper has a free version and a one-time Pro license.",
        "table_rows": [
            ("Transcribe existing files", f"{CROSS}No — LokalBot transcribes what it records", f"{CHECK}Drag and drop audio or video; export subtitles and documents"),
            ("Meeting capture", f"{CHECK}Auto-detected, bot-free microphone + system-audio tracks, summarized locally", f"{CHECK}Records Zoom, Teams, Webex, Skype, and Discord calls without a bot"),
            ("Where transcription runs", LB_ASR, "On your Mac, with a choice of local models"),
            ("AI summaries", f"{CHECK}llama.cpp built in; Ollama or OpenAI-compatible servers only if you approve them", "Connects to OpenAI, Anthropic, Google Gemini, xAI, Ollama, and other providers"),
            ("Dictation", LB_DICTATION, f"{CHECK}Real-time dictation in any app"),
            ("Transcription languages", "52 languages and dialects with the default model; 99 with Whisper", "100+"),
            ("Day timeline", LB_TIMELINE, NO),
            ("Writing autocomplete", LB_COTYPING, NO),
            ("Source code", "Open source, GPLv3", "Proprietary"),
            ("Price", "Free", "Free version · Pro €64 one-time, with lifetime updates"),
            ("Platforms", LB_PLATFORM, "macOS, plus a separate iOS app"),
        ],
        "competitor_pick_title": "Pick MacWhisper if&hellip;",
        "competitor_pick_sub": "The specialist for turning recordings into text.",
        "competitor_pick_items": [
            "You transcribe interviews, lectures, podcasts, or voice memos you already have",
            "You need subtitle files or batch transcription",
            "You like paying once for a polished single-purpose tool",
            "You want summaries from your own cloud AI keys",
        ],
        "lokal_pick_sub": "For meetings and memory, not just transcripts.",
        "lokal_pick_items": [
            "You want meeting notes with summaries and follow-ups, not only raw text",
            "You want to search across meetings and what was on your screen",
            "Free and open source matters to you",
            "You want summaries from a local model with no keys to manage",
        ],
        "faq": [
            ("Can LokalBot transcribe an existing audio file?", "Not today. LokalBot transcribes the meetings and dictation it records. For files you already have, MacWhisper is the better tool — and the two apps run fine side by side."),
            ("Which one is more private?", "Both can transcribe entirely on your Mac. The difference is in what surrounds it: LokalBot's summaries run on a built-in local model by default, and its source code is public under GPLv3, so you can check what it does with your audio."),
            ("Do they use the same speech models?", 'Partly. Both can run Whisper-family models on your Mac. LokalBot defaults to Qwen3-ASR and also offers Parakeet and Granite Speech; the <a href="benchmarks">benchmarks page</a> compares several of them on the same test set.'),
        ],
        "cta_title": "Meetings, dictation, and recall — on your Mac.",
        "disclaimer": "MacWhisper is a trademark of its owner; LokalBot is not affiliated with or endorsed by it. Details are based on public pages and pricing",
    },
    {
        "slug": "lokalbot-vs-superwhisper",
        "title": "LokalBot vs Superwhisper: local dictation and meeting notes",
        "description": "Compare Superwhisper's voice-to-text app with LokalBot's free, open-source Mac workspace for dictation, meeting notes, autocomplete, and a day timeline.",
        "og_title": "LokalBot vs Superwhisper — dictation and meeting notes compared",
        "og_description": "One is a cross-platform voice tool. The other is a free, open-source Mac workspace where dictation is one feature. An honest comparison.",
        "h1": "LokalBot vs Superwhisper",
        "competitor_name": "Superwhisper",
        "competitor_column": "Superwhisper",
        "published": "2026-07-01",
        "lead": "Superwhisper started as a dictation app and is now a cross-platform voice tool: custom modes, AI rewrites, meeting recording, and apps for Mac, Windows, iOS, and Android. If voice-to-text is your main job, it goes deeper than LokalBot. LokalBot's dictation is simpler by design — hold ⌥ Space, speak, it types — and it comes inside a free, open-source Mac app that also writes meeting notes, tracks your day, and autocompletes your writing.",
        "table_rows": [
            ("Dictation", f"{CHECK}Hold or toggle ⌥ Space, live transcript pill, pastes at the cursor", f"{CHECK}Deeper: custom modes, AI text processing, per-app behavior"),
            ("Where speech runs", f"{CHECK}{LB_ASR}", f"{CHECK}Local Whisper models, with optional cloud models"),
            ("Cloud path", "None by default; remote inference only for servers you approve", "Optional cloud models and AI processing"),
            ("Dictation audio", "Scratch recording deleted after transcription by default", '<span class="dim">Configurable in-app</span>'),
            ("Meeting notes", f"{CHECK}Bot-free microphone + system-audio capture, local summaries, searchable library", f"{CHECK}Meeting recording and transcription with automatic notes"),
            ("Day timeline", LB_TIMELINE, NO),
            ("Writing autocomplete", f"{CHECK}Cotyping ghost text as you type", f"{CROSS}No — AI modes transform what you dictate instead"),
            ("Source code", "Open source, GPLv3", "Proprietary"),
            ("Price", "Free — dictation included, nothing gated", "Free tier · Pro $8.49/mo, with yearly and lifetime options"),
            ("Platforms", LB_PLATFORM, "macOS, Windows, iOS, and Android"),
        ],
        "competitor_pick_title": "Pick Superwhisper if&hellip;",
        "competitor_pick_sub": "Dictation power users are its core audience, and it shows.",
        "competitor_pick_items": [
            "Dictation is your primary way of writing, all day",
            "You want per-app modes and AI rewriting of what you say",
            "You dictate on your phone or a Windows PC too",
        ],
        "lokal_pick_sub": "Good dictation, plus everything around it — for free.",
        "lokal_pick_items": [
            "You want dictation plus meeting notes, a day timeline, and autocomplete",
            "One model download covers your meetings and your dictation",
            "You prefer free and open source over a subscription",
            "You want local-by-default behavior you can verify in the code",
        ],
        "faq": [
            ("Which speech models does LokalBot use?", "Qwen3-ASR 1.7B by default, with Parakeet, Granite Speech, and Whisper large-v3 turbo as alternatives, all running on your Mac. Dictation reuses the engine and language you picked for meetings and keeps it warm, so transcription starts as soon as you hold the key."),
            ("Does LokalBot keep my dictation audio?", "No. By default it records to a scratch file, transcribes it on-device, pastes the text, and deletes the recording. It even pauses your music before it starts listening."),
            ("Can I run both apps?", "Sure — they use different shortcuts. Some people will want Superwhisper for heavy dictation workflows and LokalBot for meetings and everything else. LokalBot is free, so trying the combination costs nothing."),
        ],
        "cta_title": "Speak anywhere. Stays on your Mac.",
        "disclaimer": "Superwhisper is a trademark of its owner; LokalBot is not affiliated with or endorsed by it. Details are based on public pages and pricing",
    },
    {
        "slug": "lokalbot-vs-screenpipe",
        "title": "LokalBot vs Screenpipe: local screen and meeting memory",
        "description": "Compare Screenpipe's continuous screen and audio recorder with LokalBot's activity-first day timeline and bot-free meeting notes. Free, open source, for Mac.",
        "og_title": "LokalBot vs Screenpipe — local screen and meeting memory",
        "og_description": "Screenpipe records everything for your AI agents. LokalBot starts with app activity and meeting notes, and captures more only when you opt in.",
        "h1": "LokalBot vs Screenpipe",
        "competitor_name": "Screenpipe",
        "competitor_column": "Screenpipe",
        "published": "2026-09-24",
        "lead": "Screenpipe records your screen and audio continuously and turns that history into context for any AI, through a local API and MCP server. It runs on macOS, Windows, and Linux. LokalBot starts smaller: it logs app and window activity by default, adds screen text and encrypted screenshots only if you opt in, and pairs that with bot-free meeting notes. The licenses differ too — LokalBot is GPLv3 open source, while Screenpipe's source is available under a commercial license.",
        "table_rows": [
            ("Captured by default", "App name and window title; screen text and screenshots are opt-in", "Screen, audio, and meetings, continuously"),
            ("Retention and disk", "Screenshots and extracted text deleted after 14 days by default", "About 30 GB per month, with configurable retention"),
            ("Meeting notes", f"{CHECK}Bot-free microphone + system-audio capture, local summaries, searchable library", f"{CHECK}Transcription with speaker identification; a meeting-summary pipe writes notes"),
            ("Built-in AI", f"{CHECK}llama.cpp summaries and chat, no setup", "Brings your history to the AI you already use"),
            ("Connect AI tools", LB_AGENTS, "Local REST API, MCP server, and agent pipes that can take actions"),
            ("Encryption at rest", f"{CHECK}Screenshots are encrypted", "Optional"),
            ("Account required", f"{CROSS}None", "Not for the core app"),
            ("License", "Open source, GPLv3", "Source-available under the Screenpipe Commercial License"),
            ("Price", "Free", "Free (limited history) · Basic $21/mo or $250/yr · Business $42/seat/mo · Enterprise custom"),
            ("Platforms", LB_PLATFORM, "macOS 13+, Windows 10+, and Linux"),
        ],
        "competitor_pick_title": "Pick Screenpipe if&hellip;",
        "competitor_pick_sub": "Maximum capture, built as a data layer for agents.",
        "competitor_pick_items": [
            "You want everything on screen and in your ears recorded, all the time",
            "You're building agents and automations on top of a local API",
            "You use Windows, Linux, or an Intel Mac",
            "You're rolling it out to a team with managed seats",
        ],
        "lokal_pick_sub": "Recall that starts small and asks before it captures more.",
        "lokal_pick_items": [
            "You'd rather log app activity by default and opt into screen text",
            "You want meeting notes at the center, with summaries written locally",
            "You want captures cleaned up after 14 days, not 30 GB a month",
            "You want OSI-approved open source you can use at work for free",
        ],
        "faq": [
            ("Isn't Screenpipe open source?", "It used to be MIT-licensed. Current versions are source-available under the Screenpipe Commercial License: free for personal, non-profit, educational, and research use, while business use needs a paid license. LokalBot is GPLv3, so anyone can use it at work, study it, and share changes."),
            ("Does LokalBot record my screen all the time?", "No. Out of the box it saves the app name and window title. Visible text and encrypted screenshots are separate opt-ins that need macOS Accessibility and Screen Recording permission, and captures are deleted after 14 days by default."),
            ("Can AI agents read my LokalBot history?", "Yes, if you allow it. The bundled CLI and MCP server are read-only and stay off until you enable Agent Access in Settings → Privacy."),
        ],
        "cta_title": "Remember your day, on your terms.",
        "disclaimer": "Screenpipe is a trademark of its owner; LokalBot is not affiliated with or endorsed by it. Details are based on its public site, pricing, and repository",
    },
    {
        "slug": "lokalbot-vs-rewind",
        "title": "LokalBot vs Rewind: a local timeline that's still alive",
        "description": "Compare discontinued Rewind with LokalBot's local day timeline, searchable meeting notes, encrypted screenshots, and open-source Mac app.",
        "og_title": "LokalBot vs Rewind — a local timeline that's still alive",
        "og_description": "Rewind is gone. LokalBot's day timeline carries the idea forward: activity, opt-in screen text, and meetings — on your Mac, open source.",
        "h1": "LokalBot vs Rewind",
        "competitor_name": "Rewind",
        "competitor_column": "Rewind (as it was)",
        "published": "2026-07-01",
        "lead": "Rewind pioneered &ldquo;search everything you've seen on your Mac.&rdquo; Its app is now discontinued: the team pivoted to the Limitless wearable, Meta acquired Limitless in December 2025, and rewind.ai today hosts an unrelated site. LokalBot's day timeline carries the idea forward — smaller, open source, and processed on your Mac with the built-in backend.",
        "table_rows": [
            ("Status", f"{CHECK}Actively developed", "Discontinued — the team moved to Limitless, now part of Meta"),
            ("Screen memory", "App and window activity by default; opt-in screen text and encrypted screenshots, searchable by every word", "Continuous compressed screen recording, always on"),
            ("Meeting notes", f"{CHECK}Bot-free microphone + system-audio tracks, summarized locally", "Local capture; &ldquo;Ask Rewind&rdquo; answers were generated with cloud AI"),
            ("Retention", "Deleted after 14 days by default; keeping longer is an explicit opt-in", "Grew until you trimmed it yourself"),
            ("Encryption at rest", f"{CHECK}Screenshots are AES-GCM encrypted on disk", "Stored locally on disk"),
            ("Connect AI tools", LB_AGENTS, '<span class="dim">None</span>'),
            ("System-wide dictation", LB_DICTATION, NO),
            ("Writing autocomplete", LB_COTYPING, NO),
            ("Source code", "Open source, GPLv3", "Proprietary"),
            ("Price", "Free", "Was subscription-based; no longer purchasable"),
            ("Platforms", LB_PLATFORM, "macOS (app no longer available)"),
        ],
        "competitor_pick_title": "Pick Limitless (Meta) if&hellip;",
        "competitor_pick_sub": "That's where Rewind's team and ambition went.",
        "competitor_pick_items": [
            "You want a wearable that captures conversations away from the desk",
            "You're comfortable with cloud-hosted memory — now under Meta",
            "A subscription for hosted AI features is fine by you",
        ],
        "lokal_pick_sub": "You want the Rewind workflow on today's Mac — with source you can read.",
        "lokal_pick_items": [
            "A colour-coded day timeline with time-by-app totals",
            "Search every word you've seen once you opt into screen text or screenshots",
            "Ask your day questions and get answers from a local model, not a cloud API",
            "It cleans up after itself: 14-day retention by default, encrypted at rest",
        ],
        "faq": [
            ("Is LokalBot a drop-in Rewind replacement?", "Not entirely, and it doesn't try to be. Rewind recorded your screen continuously and let you scrub it like a video. LokalBot tracks app and window activity by default, and adds periodic screenshots with OCR only if you opt in — lighter on disk, easier to reason about, and combined with full meeting capture. You get the search and the timeline, not the video scrubber."),
            ("What actually happened to Rewind?", "The company behind it shifted to Limitless, a wearable pendant with cloud-hosted memory, and stopped developing the Mac app. Meta acquired Limitless in December 2025. The rewind.ai domain now hosts an unrelated service — the original app is simply gone."),
            ("How is this different from Windows Recall?", "Recall is Windows-only and drew heavy privacy scrutiny. LokalBot is for the Mac. Out of the box it logs only which app and window you had open; screen text and screenshots stay off until you turn them on. Screenshots are encrypted at rest, captures are deleted after 14 days by default, and the code that does all of that is open for you to audit."),
        ],
        "cta_title": "Your timeline, back on your Mac.",
        "disclaimer": "Rewind and Limitless are trademarks of their owners; LokalBot is not affiliated with or endorsed by them. Details are based on public reporting",
    },
]
